language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libsqlite3-dev
script:
  - mkdir build && cd build && cmake .. && cmake --build . && cmake --build . --target coveralls
