language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libsqlite3-dev
  
script:
# Build like user would do
  - mkdir Solution
  - cd Solution
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCC_OUTPUT_DIR=$(pwd)/Output -DCC_WARNING_AS_ERROR=TRUE
  - make -j $(nproc)
  - make test
  - cd ..

# Execute Cc Test-Builds.sh
  - cd Tools
  - sh Test-Builds.sh
  - cd ..
