language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libsqlite3-dev
  
script:
  - mkdir build 
  - cd build
  - cmake ../../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCC_OUTPUT_DIR=$CWD/Output -DCC_WARNING_AS_ERROR=TRUE
  - make -j $(nproc)
  - make test
