if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/CcOS/CcOS.cmake)
  execute_process(COMMAND git submodule init CcOS
                  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
  execute_process(COMMAND git submodule update CcOS
                  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
endif()

if(NOT DEFINED CCOS_CACHE_DIR)
  set( CCOS_CACHE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Cache)
  if(NOT EXISTS ${CCOS_CACHE_DIR})
    file(MAKE_DIRECTORY ${CCOS_CACHE_DIR})
  endif()
endif()

set(CCOS_BUILDLEVEL       1)
set(CCOS_LINK_TYPE        STATIC)
set(CCOS_CCKERNEL_ACTIVE  4)
set(CCOS_CCNETWORK_CCTFTP_ACTIVE  4)
set(CMAKE_CURRENT_SOURCE_DIR_BACKUP ${CMAKE_CURRENT_SOURCE_DIR})
set(CMAKE_CURRENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CcOS)
include(CcOS/CcOS.cmake)
set(CMAKE_CURRENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR_BACKUP})