set( CCOSEXAMPLEPROJECT_VERSION_MAJOR   0   )
set( CCOSEXAMPLEPROJECT_VERSION_MINOR   0   )
set( CCOSEXAMPLEPROJECT_VERSION_PATCH   1   )
set( CCOSEXAMPLEPROJECT_VERSION_BUILD   0   )
set( CCOSEXAMPLEPROJECT_VERSION_CMAKE ${CCOSEXAMPLEPROJECT_VERSION_MAJOR}.${CCOSEXAMPLEPROJECT_VERSION_MINOR}.${CCOSEXAMPLEPROJECT_VERSION_PATCH})

set( PROJECT_DESCRIPTION    "Tftp Server Project." )